authors:
 - Mikael Afzelius
 - Hugues de Riedmatten
 - Guang can Guo
 - Wolfgang Tittel
 - Tomoyuki Horikiri
 - Lars Rippe
 - Takehiko Tawara
 - Peter van Loock
 - Saikat Guha
 - Neil Sinclair
 - Rikizo Ikuta
 - Jian-Wei Pan
 - Andrew Shields
 - Toshihiko Sasaki